[tool.poetry]
name = "python-weekend-kiwi-task"
version = "0.1.0"
description = ""
authors = ["Andrea Waltlova <awaltlov@redhat.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
